"""picasso-registry: provenance & metrics database for DNA-PAINT automation."""

try:
    from ._version import version as __version__  # generated by setuptools-scm
except Exception:  # pragma: no cover - source checkout without build
    __version__ = "0.0.0+unknown"
