"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-21 15:14:59.044409
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sample_taxonomy",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("parent_id", sa.String(), nullable=True),
        sa.Column("path", sa.String(), nullable=True),
        sa.Column("ontology_ref", sa.String(), nullable=True),
        sa.Column("defaults", sa.JSON(), nullable=True),
        sa.Column("expected_metrics", sa.JSON(), nullable=True),
        sa.Column("qc_rules", sa.JSON(), nullable=True),
        sa.Column("version", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["sample_taxonomy.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "experiment",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("operator", sa.String(), nullable=True),
        sa.Column("sample_taxon_id", sa.String(), nullable=True),
        sa.Column("organism", sa.String(), nullable=True),
        sa.Column("fixation", sa.String(), nullable=True),
        sa.Column("mounting", sa.String(), nullable=True),
        sa.Column("dimensionality", sa.String(), nullable=True),
        sa.Column("buffer", sa.String(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("extra", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["sample_taxon_id"],
            ["sample_taxonomy.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "acquisition_run",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("experiment_id", sa.String(), nullable=True),
        sa.Column("microscope_id", sa.String(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("pycroflow_version", sa.String(), nullable=True),
        sa.Column("mm_version", sa.String(), nullable=True),
        sa.Column("config_yaml", sa.String(), nullable=True),
        sa.Column("raw_data_path", sa.String(), nullable=True),
        sa.Column("raw_retained", sa.Boolean(), nullable=True),
        sa.Column("extra", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiment.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reagent_provenance",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("experiment_id", sa.String(), nullable=True),
        sa.Column("prep_datetime", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hours_since_labeling", sa.Float(), nullable=True),
        sa.Column("docking_design_id", sa.String(), nullable=True),
        sa.Column("extra", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiment.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sample_tag",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("experiment_id", sa.String(), nullable=True),
        sa.Column("tag", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiment.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "target_channel",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("experiment_id", sa.String(), nullable=True),
        sa.Column("target", sa.String(), nullable=True),
        sa.Column("binder", sa.String(), nullable=True),
        sa.Column("binder_lot", sa.String(), nullable=True),
        sa.Column("dye", sa.String(), nullable=True),
        sa.Column("dye_lot", sa.String(), nullable=True),
        sa.Column("imager_seq", sa.String(), nullable=True),
        sa.Column("imager_batch", sa.String(), nullable=True),
        sa.Column("imager_conc_nM", sa.Float(), nullable=True),
        sa.Column("round_index", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiment.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "fluidics_round",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("acquisition_run_id", sa.String(), nullable=True),
        sa.Column("round_index", sa.Integer(), nullable=True),
        sa.Column("duration_s", sa.Float(), nullable=True),
        sa.Column("volume_uL", sa.Float(), nullable=True),
        sa.Column("flow_rate_uL_s", sa.Float(), nullable=True),
        sa.Column("incubation_s", sa.Float(), nullable=True),
        sa.Column("crosstalk_residual", sa.Float(), nullable=True),
        sa.Column("sensor_events", sa.JSON(), nullable=True),
        sa.Column("extra", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["acquisition_run_id"],
            ["acquisition_run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "fov",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("acquisition_run_id", sa.String(), nullable=True),
        sa.Column("target_channel_id", sa.String(), nullable=True),
        sa.Column("pos_x", sa.Float(), nullable=True),
        sa.Column("pos_y", sa.Float(), nullable=True),
        sa.Column("pos_z", sa.Float(), nullable=True),
        sa.Column("tirf_angle_deg", sa.Float(), nullable=True),
        sa.Column("exposure_ms", sa.Float(), nullable=True),
        sa.Column("frame_count", sa.Integer(), nullable=True),
        sa.Column("frame_rate_hz", sa.Float(), nullable=True),
        sa.Column("camera_temp_c", sa.Float(), nullable=True),
        sa.Column("camera_gain", sa.Float(), nullable=True),
        sa.Column("roi", sa.JSON(), nullable=True),
        sa.Column("extra", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["acquisition_run_id"],
            ["acquisition_run.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_channel_id"],
            ["target_channel.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "analysis_run",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("fov_id", sa.String(), nullable=True),
        sa.Column("acquisition_run_id", sa.String(), nullable=True),
        sa.Column("kind", sa.String(), nullable=True),
        sa.Column("compute_location", sa.String(), nullable=True),
        sa.Column("slurm_job_id", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("picasso_version", sa.String(), nullable=True),
        sa.Column("workflow_yaml", sa.String(), nullable=True),
        sa.Column("parameters", sa.JSON(), nullable=True),
        sa.Column("recommender_version", sa.String(), nullable=True),
        sa.Column("recommended_spec", sa.JSON(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("extra", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["acquisition_run_id"],
            ["acquisition_run.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fov_id"],
            ["fov.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "environment",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("fov_id", sa.String(), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("room_temp_c", sa.Float(), nullable=True),
        sa.Column("stage_temp_c", sa.Float(), nullable=True),
        sa.Column("humidity_pct", sa.Float(), nullable=True),
        sa.Column("objective", sa.String(), nullable=True),
        sa.Column("na", sa.Float(), nullable=True),
        sa.Column("immersion_lot", sa.String(), nullable=True),
        sa.Column("extra", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["fov_id"],
            ["fov.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "illumination",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("fov_id", sa.String(), nullable=True),
        sa.Column("laser_nm", sa.Integer(), nullable=True),
        sa.Column("target_power_mW", sa.Float(), nullable=True),
        sa.Column("measured_power_mW", sa.Float(), nullable=True),
        sa.Column("monet_calibration_id", sa.String(), nullable=True),
        sa.Column("extra", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["fov_id"],
            ["fov.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sample_morphology",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("fov_id", sa.String(), nullable=True),
        sa.Column("confluence", sa.Float(), nullable=True),
        sa.Column("n_cells", sa.Integer(), nullable=True),
        sa.Column("marker_intensity", sa.Float(), nullable=True),
        sa.Column("autofluorescence", sa.Float(), nullable=True),
        sa.Column("usable_fraction", sa.Float(), nullable=True),
        sa.Column("seg_features", sa.JSON(), nullable=True),
        sa.Column("extra", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["fov_id"],
            ["fov.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "artifact",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("analysis_run_id", sa.String(), nullable=True),
        sa.Column("kind", sa.String(), nullable=True),
        sa.Column("uri", sa.String(), nullable=True),
        sa.Column("checksum", sa.String(), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["analysis_run_id"],
            ["analysis_run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "feedback",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("acquisition_run_id", sa.String(), nullable=True),
        sa.Column("fov_id", sa.String(), nullable=True),
        sa.Column("analysis_run_id", sa.String(), nullable=True),
        sa.Column("operator_decision", sa.String(), nullable=True),
        sa.Column("recommender_edit", sa.JSON(), nullable=True),
        sa.Column("iteration_count", sa.Integer(), nullable=True),
        sa.Column("used_in_final", sa.Boolean(), nullable=True),
        sa.Column("failure_mode", sa.String(), nullable=True),
        sa.Column("note", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["acquisition_run_id"],
            ["acquisition_run.id"],
        ),
        sa.ForeignKeyConstraint(
            ["analysis_run_id"],
            ["analysis_run.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fov_id"],
            ["fov.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "interpretation",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("acquisition_run_id", sa.String(), nullable=True),
        sa.Column("analysis_run_id", sa.String(), nullable=True),
        sa.Column("stage1_summary", sa.String(), nullable=True),
        sa.Column("stage1_stats", sa.JSON(), nullable=True),
        sa.Column("stage2_flags", sa.JSON(), nullable=True),
        sa.Column("stage2_summary", sa.String(), nullable=True),
        sa.Column("stage3_summary", sa.String(), nullable=True),
        sa.Column("citations", sa.JSON(), nullable=True),
        sa.Column("suggested_next", sa.JSON(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("model_version", sa.String(), nullable=True),
        sa.Column("prompt_version", sa.String(), nullable=True),
        sa.Column("corpus_version", sa.String(), nullable=True),
        sa.Column("operator_feedback", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["acquisition_run_id"],
            ["acquisition_run.id"],
        ),
        sa.ForeignKeyConstraint(
            ["analysis_run_id"],
            ["analysis_run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "metrics",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("analysis_run_id", sa.String(), nullable=True),
        sa.Column("scope", sa.String(), nullable=True),
        sa.Column("n_locs", sa.BigInteger(), nullable=True),
        sa.Column("nena_nm", sa.Float(), nullable=True),
        sa.Column("frc_nm", sa.Float(), nullable=True),
        sa.Column("decorr_nm", sa.Float(), nullable=True),
        sa.Column("photons_median", sa.Float(), nullable=True),
        sa.Column("lp_x_nm", sa.Float(), nullable=True),
        sa.Column("lp_y_nm", sa.Float(), nullable=True),
        sa.Column("lp_z_nm", sa.Float(), nullable=True),
        sa.Column("psf_sigma_x", sa.Float(), nullable=True),
        sa.Column("psf_sigma_y", sa.Float(), nullable=True),
        sa.Column("psf_ellipticity", sa.Float(), nullable=True),
        sa.Column("net_gradient_median", sa.Float(), nullable=True),
        sa.Column("spots_per_frame", sa.Float(), nullable=True),
        sa.Column("usable_frame_frac", sa.Float(), nullable=True),
        sa.Column("drift_nm", sa.Float(), nullable=True),
        sa.Column("drift_residual_nm", sa.Float(), nullable=True),
        sa.Column("drift_rate_nm_min", sa.Float(), nullable=True),
        sa.Column("z_focus_residual_nm", sa.Float(), nullable=True),
        sa.Column("sbr", sa.Float(), nullable=True),
        sa.Column("background", sa.Float(), nullable=True),
        sa.Column("dark_time_s", sa.Float(), nullable=True),
        sa.Column("bright_time_s", sa.Float(), nullable=True),
        sa.Column("k_on", sa.Float(), nullable=True),
        sa.Column("k_off", sa.Float(), nullable=True),
        sa.Column("binding_freq_hz", sa.Float(), nullable=True),
        sa.Column("events_per_site", sa.Float(), nullable=True),
        sa.Column("damage_decay_rate", sa.Float(), nullable=True),
        sa.Column("duty_cycle", sa.Float(), nullable=True),
        sa.Column("density_locs_um2", sa.Float(), nullable=True),
        sa.Column("qpaint_count", sa.Float(), nullable=True),
        sa.Column("labeling_efficiency", sa.Float(), nullable=True),
        sa.Column("n_clusters", sa.Integer(), nullable=True),
        sa.Column("mean_cluster_size", sa.Float(), nullable=True),
        sa.Column("nnd_median_nm", sa.Float(), nullable=True),
        sa.Column("spinna_oligomer_fractions", sa.JSON(), nullable=True),
        sa.Column("spinna_fit_quality", sa.Float(), nullable=True),
        sa.Column("g5m_n_molecules", sa.Integer(), nullable=True),
        sa.Column("g5m_false_pos_est", sa.Float(), nullable=True),
        sa.Column("registration_error_nm", sa.Float(), nullable=True),
        sa.Column("extra", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["analysis_run_id"],
            ["analysis_run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "qc",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("analysis_run_id", sa.String(), nullable=True),
        sa.Column("passed", sa.Boolean(), nullable=True),
        sa.Column("decided_by", sa.String(), nullable=True),
        sa.Column("reason", sa.String(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["analysis_run_id"],
            ["analysis_run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "resource_usage",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("analysis_run_id", sa.String(), nullable=True),
        sa.Column("module", sa.String(), nullable=True),
        sa.Column("compute_seconds", sa.Float(), nullable=True),
        sa.Column("peak_ram_mb", sa.Float(), nullable=True),
        sa.Column("gpu_util_pct", sa.Float(), nullable=True),
        sa.Column("raw_bytes", sa.BigInteger(), nullable=True),
        sa.Column("locs_bytes", sa.BigInteger(), nullable=True),
        sa.Column("slurm_walltime_s", sa.Float(), nullable=True),
        sa.Column("slurm_cores", sa.Integer(), nullable=True),
        sa.Column("slurm_mem_mb", sa.Integer(), nullable=True),
        sa.Column("transfer_seconds", sa.Float(), nullable=True),
        sa.Column("extra", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["analysis_run_id"],
            ["analysis_run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("resource_usage")
    op.drop_table("qc")
    op.drop_table("metrics")
    op.drop_table("interpretation")
    op.drop_table("feedback")
    op.drop_table("artifact")
    op.drop_table("sample_morphology")
    op.drop_table("illumination")
    op.drop_table("environment")
    op.drop_table("analysis_run")
    op.drop_table("fov")
    op.drop_table("fluidics_round")
    op.drop_table("target_channel")
    op.drop_table("sample_tag")
    op.drop_table("reagent_provenance")
    op.drop_table("acquisition_run")
    op.drop_table("experiment")
    op.drop_table("sample_taxonomy")
    # ### end Alembic commands ###
